### ISSUE TITLE
✨feat: 부모 용돈 api 개발 ( 정기용돈 만들기 제외 )

### ISSUE THREAD

**Issue by allllfo** [ii-sol/backend-B#5]
## 📌 Description
- 정기용돈 생성,수정, 삭제를 제외한 나머지 부모 모듈의 용돈 api를 개발합니다.

## 📝 To-do
- [ ] 전체 용돈 내역 조회 (용돈 조르기, 정기용돈 포함)
- [ ] 용돈 조르기 수락, 거절
- [ ] 현재 진행중인 정기 용돈 조회하기
- [ ] 아직 승인 안한 용돈 조르기 내역 조회하기
